### ISSUE TITLE
not logging in

### ISSUE THREAD

**Issue by greg606** [sanduhrs/drupal-openid_connect#3]
Hi, 
I try to implement it with drupal/oauth2_server.
When I am redirected back to clientsite.com/en/openid-connect/generic nothing happens it just goes to /node and that's it. 
Any idea how fix it?

Warning: Cannot modify header information - headers already sent by (output started at /vendor/symfony/http-foundation/Response.php:1151) in Drupal\Core\Session\SessionManager->destroy() (line 267 of /website/core/lib/Drupal/Core/Session/SessionManager.php).

Also while debug in RedirectController I have no $tokens

Which probably is connected with this repsponse:
Could not retrieve tokens. Details: Client error: `POST http://mysite.com/oauth2/token` resulted in a `403 Forbidden` response:   <!-- FILE NAME SUGGESTIONS: \* html--system--403.html.twig \* htm (truncated...)

**Comment by greg606** [comment]
the problem were oauth server permissions.

**Comment by sanduhrs** [comment]
Just for posterity: You need to give permissions to your user to `Use OAuth2 Server` on drupal/oauth2_server side.

**Comment by greg606** [comment]
thanks ;)
