### ISSUE TITLE
impossible to create new user

### ISSUE THREAD

**Issue by uwe-k** [sanduhrs/drupal-openid_connect#6]
Hi,
i've installed 8.1.0-alpha1 in Drupal 8.0.3.
After install its impossible to create a user here /admin/people/create, because the password inputs are removed and i get a form validation error 'Password field is required.'.
I guess it happens here: hook_form_FORM_ID_alter()

Thank you

**Comment by uwe-k** [comment]
Anybody?

**Comment by sanduhrs** [comment]
Fixed that in https://www.drupal.org/node/2681221
Please try the latest development version, thanks.

**Comment by uwe-k** [comment]
Patch worked for us. Thank you
