### ISSUE TITLE
Nothing on login page

### ISSUE THREAD

**Issue by R0d3ric** [sanduhrs/drupal-openid_connect#8]
Hi,

I tried to configure your module, it seems to be ok, but nothing appears on Drupal's login page to login with OpenID Connect. I may have forgotten something but I'm unable to know what since there is no readme. Any idea please ?

Thank you !

**Comment by sanduhrs** [comment]
You need to activate the OpenID Connect Login block.
Please use https://www.drupal.org/support for support questions.

**Comment by R0d3ric** [comment]
Ok, thank you !
